name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run CI
      run: npm ci
    - name: Run Build App
      run: npm run build
      env:
        CI: ""


  build-and-deploy-react:
    name: Build and Deploy React
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-react-streaming:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-react-streaming:latest
